version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: springboot-postgres
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d productdb"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: